databases:
  - name: YUKI SAKAI_DB
    databaseName: yuki_sakai_db
    user: YUKI SAKAI
    region: singapore

services:
  - type: web
    name: YUKI SAKAI
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: YUKI SAKAI_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false